version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: adham
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
